return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      -- "astro-language-server",
      "blade-formatter",
      "css-lsp",
      "emmet-ls",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "markdownlint",
      "marksman",
      "intelephense",
      "prettier",
      "pyright",
      "ruff-lsp",
      "shellcheck",
      "shfmt",
      "sql-formatter",
      "stimulus-language-server",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "texlab",
      "typescript-language-server",
      "xmlformatter",
      "yaml-language-server",
      "netcoredbg",
      "omnisharp",
    },
  },
}
